### ISSUE TITLE
Status of the ESM upgrade

### ISSUE THREAD

**Issue by Amerr** [k2snowman69/bug-nodejs-import-cjs#1]
Hey @k2snowman69 

Appreciate your work, i have been following your comments and knowledge you have been sharing in ESM issues jest, cjs-module-lexer.

Thanks for your deep research on the core issue, why ESM is upgrading fails at multiple level. I am also undergoing the same journey, I don't know this right platform to communicate(Hopefully it reaches you). 

I wanna know, if there is any update in your journey to migrate to ESM, have you succeeded in your task. 

Either way, if it possible to share your research details or list of tech documents.
It would really save my time.

Thanks ❤️  for your detailed comments

**Comment by k2snowman69** [comment]
Once they resolved the bug in Jest that referenced this repo I didn't have any issues and everything upgraded fine.

Most of my repos are now ESM (if not all) however the one repo I keep most up to date is [Sortier](https://github.com/snowcoders/sortier/blob/main/package.json#L91)

Good luck on your upgrade!

**Comment by k2snowman69** [comment]
closing due to quietness
